import numpy as np

def numberOfDivisors(number):
    return n_divisors

def isNumberTriangular(number):
    return boolean

def retrieveValues():
    problem = """The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 
    1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. We can see that 28 is the first triangle to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?
    """

    code = """
    """

    solution = question12()

    return problem, code, solution